### PR TITLE
Social Network

### PR DESCRIPTION
**Pull request by vikitaotiz**
This project entails a social media application built using rails.
It has a scaffold of the minimum viable product.
I have added associations between the user, friendship, and like models

### CODE REVIEW

**Review by george-shammar — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUIRED** :recycle: :recycle: 

Hello Victor, 
Decent effort, your repo looks professional without linter errors.

As discussed with you on slack, this is the first milestone and requires an ERD.

- [ ] Please add an ERD according to the project requirement.
- [ ] Also, make the development branch your default branch.


Please submit another CRR when you're ready. 

Cheers and happy coding :smile:

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
--------------
Hello @vikitaotiz  great job working on the required changes :+1: :clap: 
However, there is a minor changes to make :hammer_and_wrench: see them below :eyes: :point_down: 
-------------

- [ ] User table has image_link column. Please add this column to the User table. 

imglink

-------------------
Please make this minor change and send it again for another review :clap: :muscle: 
HAPPY CODING!!!

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, thank you for working on changes suggested previously :ok_hand:

## To Improve 🙏
- [ ] User table should have `image_link` column. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/imglink.png).

### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Review by MkrtichSargsyan — APPROVED** [review]
## _Status:_ Approved  :hamster: :rocket:
Hello :wave:.

Awesome job on this project.:rocket: You have completed all the requested changes from the previous code reviewer.

You can go ahead and merge this branch to the base branch of this repo.
Good luck in your future projects and happy coding :relaxed:

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Pull request merged**
