### PR TITLE
Add frienship model to the application

### PR DESCRIPTION
**Pull request by vikitaotiz**
Friendship model allows users to send a friend request to other logged-in users.
Users can either accept or reject sent friend requests.
Users can also see a list of their friends.

Just in case, I already did friendship version one and its association on the first milestone

### CODE REVIEW

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- User model has_many :friendships :+1: 
- Friendship model belongs_to :user :100: 
- Friendship model belongs_to :friend, class_name: "User" :+1: 
- User can invite friends :+1: 
- User can see friendships requests :+1: 

To improve :factory_worker: [REQUIRED]:

- [ ] There is a button to invite user to friendship **on users list page** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] Posts timeline includes posts written by logged-in user **and their friends** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] Good job by adding indexes. It will be nice if post_id and user_id inside comments, likes, and posts tables are also an FK.
- [ ] It will be nice if `user A` cannot send a friend request to `user B` if `user A` has already received a friend request from `user B`
- [ ] Please add more test units, the aim is to make sure that your APP runs as expected.

Nice to have [OPTIONAL] :

- [ ] Please read about n+1 and make sure there is no n + 1 queries in index views
- [ ] It will be nice if there are no logic in your views

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by george-shammar — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUIRED** :recycle: :recycle: 

Really impressive. You have implemented all but one required changes.

Please see below:

- [ ] Posts timeline includes posts written by logged-in user and their friends. Currently, every user could see posts from everybody irrespective of their friendship status. Please fix it.

Please submit another CRR when you're ready.

Drop your message here if you require any clarification.

Cheers and happy coding. :smile:

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coder, 👋🏽 
**This is a great project you have going on, well-done lad and thanks for implementing the changes requested earlier on**. 

### Well-done 💯 
    1. The app runs just fine

**However, there is one section to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [ ] Currently, the users' timeline has only their post even when they already have friends. Look into this and ensure that their timeline includes their own posts and those of their friends.

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
--------------------
Hello @vikitaotiz great job you are doing on this milestone :+1: :clap: 
However, there is a minor change to make to complete this milestone :hammer_and_wrench: see them below :eyes: :point_down: 
-------------

- [ ] When I send a friend request I can see the post from the user that I send the friend request without the user accept the friendship. Please fix this so I only can see posts from users that accept the friendship. 
 ----------------
Please make thIS required change and send it again for another review :1st_place_medal: :100: 
HAPPY CODING!!!

tenor (1)

**Review by elisha2kyakpo1 — APPROVED** [review]
# Status: Approved💪🎉✔
**Congratulations on reaching this far! I'm really happy to see the changes which were requested.**

Happy coding💪

Elisha

**Pull request merged**
